### ISSUE TITLE
Are those pb files you provided frozen ones?

### ISSUE THREAD

**Issue by KleinYuan** [IDLabs-Gate/enVision#3]
I trained my own tiny yolo model and translated it into `pb` files with [YOLO_tensorflow](https://github.com/gliese581gg/YOLO_tensorflow). When I replace the `tiny-yolo-opt.pb` with my own one, I see errors complaining:

```
${path}/enVision/enVision/tensorflow_utils.mm:185] MMap failed with Corrupted memmapped model file: /var/containers/Bundle/Application/7BDE51AD-B72D-480C-9B12-4D73B97C96F3/enVision.app/yolo-tiny-opt.pb Invalid directory offset

${path}/enVision/enVision/tfWrap.mm:78] Couldn't load model: Data loss: Corrupted memmapped model file: /var/containers/Bundle/Application/7BDE51AD-B72D-480C-9B12-4D73B97C96F3/enVision.app/yolo-tiny-opt.pb Invalid directory offset
```

Do I need to freeze it?

Is it possible for you guys to document/elaborate more on how you get those `pb` files?

**Comment by Mu7ammad** [comment]
Most likely your pb graph is not memory mapped, which is the last step of mobile deployment optimizations. You can either pass it through the scripts provided by TensorFlow to prepare for mobile deployment as described here:
https://petewarden.com/2016/09/27/tensorflow-for-mobile-poets/
Or else use unmapped, just make sure you are calling the correct loadModel() method of the tfWrap object with memMapped parameter = False. Examples of using it with memMapped=True are in the load() method of YOLO class in YOLO.swfit
Note that if you are using the newest version of TensorFlow 1.x it may not work as-is. The dependencies in the "tf" folder downloaded separately are extracted and built from version 0.11, so you will need to build TensorFlow for iOS of same version as the one used to build and freeze your model and link the Xcode project against it directly (instead of the current tf folder dependencies) as described here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile

**Comment by KleinYuan** [comment]
@Mu7ammad  Thanks for your quick response!

I think that's probably why.
It will be great if you can share `Yolo->tensorflow` translation process. But anyway, I will give it another try. Will update here if I got my own trained model work.

**Comment by KleinYuan** [comment]
@Mu7ammad I replaced the tf folder that you provided with 1.1.0, also turned off the memmap and it can now load directly translated model now. Result is a little interesting but that can be another issue/story. We can close this issue now. Thanks for your advice.

**Comment by KleinYuan** [comment]
@Mu7ammad Tiny yolo model should be just around 60MB and why yours is as large as 180MB?

**Comment by Mu7ammad** [comment]
This is a tiny yolo of version 1 not version 2 of 60 MB

**Comment by KleinYuan** [comment]
@Mu7ammad ok, I got it working perfectly with my own trained model. you rock man!
